In [2]:
import numpy as np

In [2]:
list1 = [1,2,3]
list2 = [4,5,6]
m = np.array([list1,list2])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
#通过步长创建array
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [4]:
#将n转换成3*5的array
n = n.reshape(3, 5) 
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [5]:
#将0~4平均分成9份放入array
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [6]:
#resize()改变维度
o.resize((3, 3))
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [7]:
#创建一个都为1的阵列
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#对角阵列，其余为0
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#带参数的对角阵列
y = [4,5,6]
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [11]:
#重复创建，注意两者区别
print(np.array([1, 2, 3] * 3))
print(np.repeat([1, 2, 3], 3))

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [12]:
#堆叠
p = np.ones([2, 3],int)
##垂直堆叠
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [13]:
##水平堆叠
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [14]:
#运算
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x + y)
print(x * y)
print(x ** y)

[5 7 9]
[ 4 10 18]
[  1  32 729]


In [15]:
#矩阵乘法
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [16]:
#矩阵转置 .T
z = np.array([y,2*y])
z

array([[ 4,  5,  6],
       [ 8, 10, 12]])

In [17]:
#类型及其转换
print(z.dtype)
#int32
z = z.astype('f')
print(z.dtype)

int32
float32


In [18]:
#数学公式
a = np.array([-4, -2, -1, 2, 4])
a.sum()

-1

In [19]:
a.max()

4

In [20]:
a.min()

-4

In [21]:
#平均值
a.mean()

-0.2

In [22]:
#标准差
a.std()

2.85657137141714

In [23]:
#最大值索引 4
a.argmax()

4

In [24]:
#最小值索引 0
a.argmin()

0

In [25]:
#矩阵索引
r = np.arange(36)
r.resize((6, 6))
r


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [26]:
#切片
r[2::2,2::2]

array([[14, 16],
       [26, 28]])

In [27]:
#14 行列的索引都从0开始
r[3,3:6]

array([21, 22, 23])

In [28]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [29]:
#r2更改时r也会随着更改
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [30]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [32]:
#.copy() 复制一个与原矩阵不同地址的矩阵
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [33]:
r_copy[:] = 10
print(r_copy)
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


In [34]:
test = np.random.randint(0, 10, (4, 3))
test

array([[8, 8, 6],
       [2, 8, 9],
       [4, 3, 1],
       [0, 3, 6]])

In [35]:
#迭代矩阵
for row in test:
    print(row)

[8 8 6]
[2 8 9]
[4 3 1]
[0 3 6]


In [36]:
#test[i] 代表第i行，i为索引，从0开始
for i in range(len(test)):
    print(test[i])
print(len(test))
print(test[2])

[8 8 6]
[2 8 9]
[4 3 1]
[0 3 6]
4
[4 3 1]


In [37]:
#内置行数enumerate()，i为索引，row为行内容，类似于dict.items()
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [8 8 6]
row 1 is [2 8 9]
row 2 is [4 3 1]
row 3 is [0 3 6]


In [38]:
test2 = test ** 2
test2

array([[64, 64, 36],
       [ 4, 64, 81],
       [16,  9,  1],
       [ 0,  9, 36]], dtype=int32)

In [39]:
test3 = test *2
test3

array([[16, 16, 12],
       [ 4, 16, 18],
       [ 8,  6,  2],
       [ 0,  6, 12]])

In [40]:
#zip()遍历多个矩阵
for i, j, n in zip(test, test2, test3):
    print(i, '+', j, '+', n, '=', i + j + n)

[8 8 6] + [64 64 36] + [16 16 12] = [88 88 54]
[2 8 9] + [ 4 64 81] + [ 4 16 18] = [ 10  88 108]
[4 3 1] + [16  9  1] + [8 6 2] = [28 18  4]
[0 3 6] + [ 0  9 36] + [ 0  6 12] = [ 0 18 54]
